SunEom/SE2022-Team3

- frontend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/Screens/Login/LoginPresenter.jsx
- frontend/src/Screens/firebase.js
Firebase 연동을 위한 Configuration을 설정하였습니다.
> Frontend Firebase 연결을 위한 Configuration을 설정하였습니다.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/Screens/Login/LoginContainer.jsx
- frontend/src/Screens/Login/LoginMethod.js
- frontend/src/Screens/Login/LoginPresenter.jsx
- frontend/src/store.js
* 로그인 버튼을 눌러도 로그인 요청을 하지 않는 것을 수정하였습니다.
* 로그인을 위한 기본 프로세스를 작성하였습니다.
* Redux 기본 설정을 마쳤습니다.
* Google 로그인 요청을 하는 프로세스를 추가하였습니다
> Login process

- README.md
> README.md를 업데이트 하였습니다.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/Presenter/Components/Drawer/DrawerContainer.jsx
- frontend/src/Presenter/Components/Drawer/DrawerPresenter.jsx
- frontend/src/Presenter/Components/Drawer/index.js
- frontend/src/Presenter/Components/Header/HeaderContainer.jsx
- frontend/src/Presenter/Components/Header/HeaderPresenter.jsx
> 기본 Drawer UI를 추가하였습니다.

- backend/build.gradle
- backend/src/main/java/closet/backend/BackendApplication.java
- backend/src/test/java/closet/backend/BackendApplicationTests.java
> Backend RE-Initialize

- Closet.mdj
- backend/.gitignore
- backend/build.gradle
- backend/src/main/java/closet/backend/config/FirebaseConfig.java
- backend/src/main/java/closet/backend/config/JdbcConfig.java
- backend/src/main/java/closet/backend/controller/UserController.java
- backend/src/main/java/closet/backend/dao/UserDao.java
- backend/src/main/java/closet/backend/dao/UserDaoImpl.java
- backend/src/main/java/closet/backend/dto/UserDto.java
- backend/src/main/java/closet/backend/entity/BaseEntity.java
- backend/src/main/java/closet/backend/entity/Cloth.java
- backend/src/main/java/closet/backend/entity/Post.java
- backend/src/main/java/closet/backend/entity/User.java
- backend/src/main/java/closet/backend/service/UserService.java
- backend/src/main/resources/application.properties
- backend/src/test/java/closet/backend/JDBCTemplateTest.java
> 클래스 다이어그램 일부 작성

- Closet(ver 1.1).mdj
> 클래스 다이어그램 재 업로드

- frontend/src/Presenter/Screens/Main/MainPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/PostDetailContainer.jsx
- frontend/src/Presenter/Screens/PostDetail/PostDetailPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/index.js
- frontend/src/index.js
> 게시글 디테일 페이지 작성 완료

- frontend/src/Presenter/Screens/PostDetail/PostDetailPresenter.jsx
게시물 디테일 화면구성 1차 수정했습니다
-추가로 댓글 '400자 글자 제한' 보이는 기능 구현 필요
> 게시물 디테일 화면구성 수정

- frontend/src/Presenter/Screens/PostDetail/Component/CommentItem/CommentItemContainer.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentItem/CommentItemPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentItem/index.js
- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/CommentsListContainer.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/CommentsListPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/index.js
- frontend/src/Presenter/Screens/PostDetail/PostDetailPresenter.jsx
게시물 디테일 페이지에서
1. 댓글 아이콘과 좋아요 버튼 위치 수정 및 크기 변경
2. 댓글입력창과 댓글 리스트 위치 변경하였습니다.
> 게시물 디테일 페이지 화면 구성 2차 수정

- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/CommentsListPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/PostDetailPresenter.jsx
PostDetail 컴포넌트 파일 import문 수정했습니다
> PostDetail 컴포넌트 파일 import문 수정

- frontend/src/Presenter/Screens/PostDetail/Component/CommentItem/CommentItemContainer.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentItem/CommentItemPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/CommentsListContainer.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/CommentsListPresenter.jsx
게시판 디테일 페이지 댓글  map함수로 댓글 리스트 출력하는 부분 추가하였습니다.
> 게시판 디테일페이지 댓글부분  추가

- frontend/src/httpRequest.js
axios를 이용하여 서버에 요청하는 함수를 모두 추가하였습니다.
> http 요청을 위한 메서드를 추가하였습니다.

- React Flowchart.mdj
* 요구사항 명세서에 회원 탈퇴에 대한 내용을 추가하였습니다.
* FlowChart에 회원 탈퇴에 대한 내용을 추가하였습니다.
> 요구사항 명세서 및 클래스 다이어그램을 수정하였습니다.

- React Flowchart.mdj
#82 의 클래스 다이어그램 수정에서 발생한 다이어그램 상의 오류를 수정하였습니다.
> 클래스 다이어그램을 수정하였습니다.

- backend/src/main/java/closet/backend/controller/ClothController.java
- backend/src/main/java/closet/backend/controller/ClothFolderController.java
- backend/src/main/java/closet/backend/controller/ClothRecommnedController.java
- backend/src/main/java/closet/backend/controller/CommentController.java
- backend/src/main/java/closet/backend/controller/MypageController.java
- backend/src/main/java/closet/backend/controller/PostController.java
- backend/src/main/java/closet/backend/dao/ClothDao.java
- backend/src/main/java/closet/backend/dao/ClothDaoImpl.java
- backend/src/main/java/closet/backend/dao/ClothFolderDao.java
- backend/src/main/java/closet/backend/dao/ClothFolderDaoImpl.java
- backend/src/main/java/closet/backend/dao/ClothFolderDetailDao.java
- backend/src/main/java/closet/backend/dao/ClothFolderDetailDaoImpl.java
- backend/src/main/java/closet/backend/dao/CommentDao.java
- backend/src/main/java/closet/backend/dao/CommentDaoImpl.java
- backend/src/main/java/closet/backend/dao/FavoritePostDao.java
- backend/src/main/java/closet/backend/dao/FavoritePostDaoImpl.java
- backend/src/main/java/closet/backend/dao/PostDao.java
- backend/src/main/java/closet/backend/dao/PostDaoImpl.java
- backend/src/main/java/closet/backend/dao/UserDaoImpl.java
- backend/src/main/java/closet/backend/dto/UserDto.java
- backend/src/main/java/closet/backend/entity/User.java
- backend/src/main/java/closet/backend/service/ClothFolderService.java
- backend/src/main/java/closet/backend/service/ClothRecommendService.java
- backend/src/main/java/closet/backend/service/ClothService.java
- backend/src/main/java/closet/backend/service/CommentService.java
- backend/src/main/java/closet/backend/service/MyPageService.java
- backend/src/main/java/closet/backend/service/PostService.java
- cleset(ver 1.7).mdj
* 기본 컨트롤러 클래스 생성
* 기본 서비스 클래스 생성
* 기본 dao 인터페이스 및 구현 클래스 생성
> class 및 interface 생성

- frontend/src/Presenter/Components/BoardTable/BoardTableContainer.jsx
- frontend/src/Presenter/Screens/Board/BoardContainer.jsx
- frontend/src/Presenter/Screens/Board/BoardPresenter.jsx
* 게시판의 장르를 변경해도 타이틀이 변경되지 않는 오류를 수정하였습니다.
* 카테고리 변경시 게시판의 목록이 첫 페이지부터 시작하지 않는 오류를 수정하였습니다.
> 게시판 화면의 오류를 수정하였습니다.

- backend/src/main/java/closet/backend/controller/MyPageController.java
> 마이페이지 기능 구현 완료

- backend/src/main/java/closet/backend/config/WebConfig.java
> CORS config 설정

- backend/src/main/java/closet/backend/controller/ClothRecommendController.java
- backend/src/main/java/closet/backend/service/ClothRecommendService.java
> 의상 추천 기능 구현

- frontend/src/Presenter/Router/RouterContainer.jsx
- frontend/src/Presenter/Screens/Login/LoginContainer.jsx
- frontend/src/Presenter/Screens/Main/MainPresenter.jsx
- frontend/src/Presenter/Screens/Main/components/Suggestion/SuggestionContainer.jsx
- frontend/src/Presenter/Screens/MyPage/components/Account/AccountContainer.jsx
- frontend/src/Presenter/Screens/MyPage/components/InfoEdit/InfoEditContainer.jsx
- frontend/src/Presenter/Screens/MyPage/components/MyInfo/MyInfoContainer.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentItem/CommentItemPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/CommentsListContainer.jsx
- frontend/src/Presenter/Screens/PostDetail/Component/CommentsList/CommentsListPresenter.jsx
- frontend/src/httpRequest.js
> Spring 서버와 통신하여 작동하도록 수정하였습니다.

- frontend/src/Presenter/Screens/PostDetail/PostDetailPresenter.jsx
- frontend/src/Presenter/Screens/Posting/PostingContainer.jsx
- frontend/src/Presenter/Screens/Posting/PostingPresenter.jsx
- frontend/src/httpRequest.js
> 게시글 작성 페이지 수정

- backend/src/main/java/closet/backend/controller/ClothController.java
- backend/src/main/java/closet/backend/controller/ClothFolderController.java
- backend/src/main/java/closet/backend/dao/ClothDaoImpl.java
- backend/src/main/java/closet/backend/dao/ClothFolderDaoImpl.java
- backend/src/main/java/closet/backend/dto/CreateFolderDto.java
- backend/src/main/java/closet/backend/req/ChangeFavoriteReq.java
- backend/src/main/java/closet/backend/req/ClothInFolderReq.java
- backend/src/main/java/closet/backend/req/ClothIntoFolderReq.java
- backend/src/main/java/closet/backend/req/CreateClothReq.java
- backend/src/main/java/closet/backend/req/CreateFolderReq.java
- backend/src/main/java/closet/backend/req/DeleteClothInFolderReq.java
- backend/src/main/java/closet/backend/req/DeleteClothReq.java
- backend/src/main/java/closet/backend/req/DeleteFolderReq.java
- backend/src/main/java/closet/backend/req/GetClothByCategoryReq.java
- backend/src/main/java/closet/backend/req/GetClothBySeasonReq.java
- backend/src/main/java/closet/backend/req/UpdateClothReq.java
- backend/src/main/java/closet/backend/service/ClothFolderService.java
- backend/src/main/java/closet/backend/service/ClothService.java
- backend/src/main/java/closet/backend/util/FileUtil.java
* 의상 관련 기능들을 구현 하였습니다.
* 파일 저장 경로를 상대 경로화 하였습니다.
> 의상 관련 기능 구현

- backend/build.gradle
- backend/src/main/java/closet/backend/config/SecurityConfig.java
- backend/src/main/java/closet/backend/config/WebConfig.java
- backend/src/main/java/closet/backend/dao/cloth/ClothDaoImpl.java
- backend/src/main/java/closet/backend/dao/post/PostDaoImpl.java
- backend/src/main/java/closet/backend/service/ClothRecommendService.java
- backend/src/main/resources/application.properties
* 게시글 및 의상 등록시에 이미지가 즉시 표현 되도록 수정 하였습니다.
> 게시글 및 의상 등록시 이미지 즉시 게시하도록 수정

- frontend/src/Presenter/Screens/PostDetail/Component/CommentItem/CommentItemPresenter.jsx
- frontend/src/Presenter/Screens/PostDetail/PostDetailPresenter.jsx
- frontend/src/util.js
* 자신이 작성한 게시글에만 수정 삭제 버튼이 보이도록 수정하였습니다.
* 자신이 작성한 댓글에만 수정 삭제 버튼이 보이도록 수정하였습니다. 
* 댓글에 작성자의 닉네임이 표시되도록 수정하였습니다.
> 게시글과 댓글UI를 수정하였습니다.

- frontend/src/Presenter/Screens/Main/components/ClassificationListItem/ClassificationListItemContainer.jsx
- frontend/src/Presenter/Screens/Main/components/ClassificationListItem/ClassificationListItemPresenter.jsx
- frontend/src/Presenter/Screens/Main/components/DetailModal/DetailModalPresenter.jsx
> 의상 상세 화면을 수정하였습니다.
